// GENERATED by `cargo run -p xtask -- spell types`. Do not edit by hand.
//
// Source of truth: crates/spellcraft-engine/src/export.rs in the
// SoulsSpellCraft-engine repo. Regenerate and diff after any change there.

export type SpellDocument = { schemaVersion: number, 

graphSchemaVersion: number, walkerVersion: number, source: DocumentSource, spell: SpellSummary, nodes: Array<DocNode>, edges: Array<DocEdge>, 

fieldMeta: { [key in string]: ParamTypeMeta }, 

linkFields: { [key in string]: LinkFields }, diagnostics: Array<DocDiagnostic>, };

export type DocumentSource = { 

regulationSha256: string | null, paramdexFingerprint: string | null, };

export type SpellSummary = { magicId: number, name: string | null, iconId: number | null, 

textSource: string, summary: string | null, description: string | null, classifications: Array<string>, 

generatedRowCount: number, };

export type DocNode = { 

key: string, kind: string, id: number, name: string | null, status: string, 

statusDetail: string | null, 

paramType: string | null, 

table: string | null, 

castTypes: Array<string>, 

fields: Array<DocField>, };

export type DocField = { name: string, value: DocValue, };

export type DocValue = { "type": "int", "value": number } | { "type": "float", "value": number } | { "type": "double", "value": number } | { "type": "str", "value": string } | { "type": "bytes", "value": string };

export type DocEdge = { from: string, to: string, 

field: string, 

resolution: string, 

castType: string | null, refCategory: number | null, consumeType: number | null, };

export type ParamTypeMeta = { paramType: string, description: string | null, fields: { [key in string]: FieldMeta }, };

export type FieldMeta = { displayName: string | null, description: string | null, };

export type LinkFields = { 

atk: Array<string>, 

bullet: Array<string>, 

spEffect: Array<string>, 

spEffectVfx: Array<string>, 

sfx: Array<string>, 

uncategorized: Array<string>, };

export type DocDiagnostic = { node: string | null, field: string | null, kind: string, detail: string, };

export type SpellIndex = { schemaVersion: number, graphSchemaVersion: number, walkerVersion: number, source: DocumentSource, 

spells: Array<SpellIndexEntry>, };

export type SpellIndexEntry = { magicId: number, 

file: string, name: string | null, iconId: number | null, classifications: Array<string>, nodeCount: number, edgeCount: number, 

generatedRowCount: number, diagnosticCount: number, 

unresolvedNodeCount: number, };

export type SpellPatch = { schemaVersion: number, 

base: DocumentSource, 

magicId: number, 

note: string | null, edits: Array<FieldEdit>, };

export type FieldEdit = { 

node: string, 

field: string, 

value: DocValue, 

expected: DocValue | null, };

export type CraftPatch = { schemaVersion: number, 

base: DocumentSource, 

targetId: number, note: string | null, 

name: string | null, 

info: string | null, 

caption: string | null, rows: Array<CraftRow>, 

edits: Array<FieldEdit>, };

export type CraftRow = { 

table: string, 

cloneFrom: number, 

id: number | null, overrides: { [key in string]: DocValue }, };

export const EXPORT_SCHEMA_VERSION = 4;
export const PATCH_SCHEMA_VERSION = 1;
export const CRAFT_PATCH_SCHEMA_VERSION = 1;
export const GRAPH_SCHEMA_VERSION = 1;
export const WALKER_VERSION = 1;

export type Incompatibility = {
  field: 'schemaVersion' | 'graphSchemaVersion' | 'walkerVersion';
  found: number;
  expected: number;
  fatal: boolean;
};

/** Every version disagreement between a document and this build, worst first. */
export function checkVersions(doc: SpellDocument): Incompatibility[] {
  const checks: Incompatibility[] = [
    {
      field: 'schemaVersion',
      found: doc.schemaVersion,
      expected: EXPORT_SCHEMA_VERSION,
      fatal: true,
    },
    {
      field: 'graphSchemaVersion',
      found: doc.graphSchemaVersion,
      expected: GRAPH_SCHEMA_VERSION,
      fatal: false,
    },
    {
      field: 'walkerVersion',
      found: doc.walkerVersion,
      expected: WALKER_VERSION,
      fatal: false,
    },
  ];
  return checks
    .filter((c) => c.found !== c.expected)
    .sort((a, b) => Number(b.fatal) - Number(a.fatal));
}


export function parseSpellDocument(text: string): SpellDocument {
  const doc = JSON.parse(text) as SpellDocument;
  for (const bad of checkVersions(doc)) {
    const detail =
      `spell document ${bad.field} ${bad.found} != ${bad.expected} expected by this build`;
    if (bad.fatal) {
      throw new Error(
        `${detail} — re-run \`xtask spell export\` against the same engine.`,
      );
    }
    console.warn(
      `${detail}. The document is readable but may not match a fresh walk; ` +
        `re-export to be sure.`,
    );
  }
  return doc;
}

export function parseSpellIndex(text: string): SpellIndex {
  const index = JSON.parse(text) as SpellIndex;
  if (index.schemaVersion !== EXPORT_SCHEMA_VERSION) {
    throw new Error(
      `spell index schemaVersion ${index.schemaVersion} != ${EXPORT_SCHEMA_VERSION} ` +
        `expected by this build — re-run \`xtask spell export --all\`.`,
    );
  }
  return index;
}
